### ISSUE TITLE
slight change in UI?  for consistency.  I don't think I can change this... 

### ISSUE THREAD

**Issue by publicsphere** [smrose/ps#18]
**current PGHCI page**
Welcome back Doug Schuler. Edit your assessment by clicking [here](https://labs.publicsphereproject.org/ps/PGHCI/index.php?assess=1).

Edit or enter your own patterns [here](https://labs.publicsphereproject.org/ps/PGHCI/index.php?pattern=1).

**how it should be**
Welcome back Doug Schuler. 

[Edit your assessment](https://labs.publicsphereproject.org/ps/PGHCI/index.php?assess=1).

[Edit or enter your own patterns](https://labs.publicsphereproject.org/ps/PGHCI/index.php?pattern=1).

**Comment by smrose** [comment]
I agree that this is better, and that it's not changeable without editing code (specifically, `project/index.php`).  Done.
